//
// Generated file, do not edit! Created by opp_msgtool 6.2 from BFSRoutingPacket.msg.
//

#ifndef __BFSROUTINGPACKET_M_H
#define __BFSROUTINGPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class BFSRoutingPacket;
/**
 * Class generated from <tt>BFSRoutingPacket.msg:6</tt> by opp_msgtool.
 * <pre>
 * packet BFSRoutingPacket
 * {
 *     string type;
 *     int sourceAddress;
 *     int destinationAddress;
 *     int hopCount = 0;
 *     int requestId;
 * }
 * </pre>
 */
class BFSRoutingPacket : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string type;
    int sourceAddress = 0;
    int destinationAddress = 0;
    int hopCount = 0;
    int requestId = 0;

  private:
    void copy(const BFSRoutingPacket& other);

  protected:
    bool operator==(const BFSRoutingPacket&) = delete;

  public:
    BFSRoutingPacket(const char *name=nullptr, short kind=0);
    BFSRoutingPacket(const BFSRoutingPacket& other);
    virtual ~BFSRoutingPacket();
    BFSRoutingPacket& operator=(const BFSRoutingPacket& other);
    virtual BFSRoutingPacket *dup() const override {return new BFSRoutingPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getType() const;
    virtual void setType(const char * type);

    virtual int getSourceAddress() const;
    virtual void setSourceAddress(int sourceAddress);

    virtual int getDestinationAddress() const;
    virtual void setDestinationAddress(int destinationAddress);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual int getRequestId() const;
    virtual void setRequestId(int requestId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BFSRoutingPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BFSRoutingPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline BFSRoutingPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<BFSRoutingPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __BFSROUTINGPACKET_M_H

