//
// Generated file, do not edit! Created by opp_msgtool 6.2 from BFSRoutingPacket.msg.
//

#ifndef __BFSROUTINGPACKET_M_H
#define __BFSROUTINGPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class BFSRoutingPacket;
/**
 * Class generated from <tt>BFSRoutingPacket.msg:6</tt> by opp_msgtool.
 * <pre>
 * packet BFSRoutingPacket
 * {
 *     string type;
 *     int sourceAddress;
 *     int destinationAddress;
 *     int hopCount = 0;
 *     int requestId;
 * 
 *     // A* algorithm fields
 *     double gCost = 0.0;        // Actual cost from source (g(n))
 *     double hCost = 0.0;        // Heuristic cost to destination (h(n))
 *     double fCost = 0.0;        // Total cost f(n) = g(n) + h(n)
 * 
 *     // Path tracking
 *     int pathLength = 0;        // Number of nodes in path
 *     int path[10];              // Stores the path taken (node addresses)
 * 
 *     // Quality metrics
 *     double cumulativeDelay = 0.0;  // Total delay accumulated
 *     simtime_t timestamp;           // When packet was created
 * 
 *     // RSA Encryption fields - only path information is encrypted
 *     bool isEncrypted = false;          // Flag indicating if path info is encrypted
 *     long encryptedHopCount = 0;        // Encrypted hop count (path length)
 * 
 *     // NOTE: Costs (g, h, f) are NOT encrypted - they are calculated locally
 *     // at each node based on the decrypted hop count and local measurements
 *     // Only the encrypted fields below are used:
 *     long encryptedGCost = 0;           // Reserved (not used)
 *     long encryptedHCost = 0;           // Reserved (not used)
 *     long encryptedFCost = 0;           // Reserved (not used)
 * 
 *     // RSA Public Key of sender (for secure communication)
 *     long senderPublicKey = 0;          // Public exponent (e)
 *     long senderModulus = 0;            // Modulus (n)
 * }
 * </pre>
 */
class BFSRoutingPacket : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string type;
    int sourceAddress = 0;
    int destinationAddress = 0;
    int hopCount = 0;
    int requestId = 0;
    double gCost = 0.0;
    double hCost = 0.0;
    double fCost = 0.0;
    int pathLength = 0;
    int path[10] = {0};
    double cumulativeDelay = 0.0;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    bool isEncrypted_ = false;
    long encryptedHopCount = 0;
    long encryptedGCost = 0;
    long encryptedHCost = 0;
    long encryptedFCost = 0;
    long senderPublicKey = 0;
    long senderModulus = 0;

  private:
    void copy(const BFSRoutingPacket& other);

  protected:
    bool operator==(const BFSRoutingPacket&) = delete;

  public:
    BFSRoutingPacket(const char *name=nullptr, short kind=0);
    BFSRoutingPacket(const BFSRoutingPacket& other);
    virtual ~BFSRoutingPacket();
    BFSRoutingPacket& operator=(const BFSRoutingPacket& other);
    virtual BFSRoutingPacket *dup() const override {return new BFSRoutingPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getType() const;
    virtual void setType(const char * type);

    virtual int getSourceAddress() const;
    virtual void setSourceAddress(int sourceAddress);

    virtual int getDestinationAddress() const;
    virtual void setDestinationAddress(int destinationAddress);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual int getRequestId() const;
    virtual void setRequestId(int requestId);

    virtual double getGCost() const;
    virtual void setGCost(double gCost);

    virtual double getHCost() const;
    virtual void setHCost(double hCost);

    virtual double getFCost() const;
    virtual void setFCost(double fCost);

    virtual int getPathLength() const;
    virtual void setPathLength(int pathLength);

    virtual size_t getPathArraySize() const;
    virtual int getPath(size_t k) const;
    virtual void setPath(size_t k, int path);

    virtual double getCumulativeDelay() const;
    virtual void setCumulativeDelay(double cumulativeDelay);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);

    virtual bool isEncrypted() const;
    virtual void setIsEncrypted(bool isEncrypted);

    virtual long getEncryptedHopCount() const;
    virtual void setEncryptedHopCount(long encryptedHopCount);

    virtual long getEncryptedGCost() const;
    virtual void setEncryptedGCost(long encryptedGCost);

    virtual long getEncryptedHCost() const;
    virtual void setEncryptedHCost(long encryptedHCost);

    virtual long getEncryptedFCost() const;
    virtual void setEncryptedFCost(long encryptedFCost);

    virtual long getSenderPublicKey() const;
    virtual void setSenderPublicKey(long senderPublicKey);

    virtual long getSenderModulus() const;
    virtual void setSenderModulus(long senderModulus);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BFSRoutingPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BFSRoutingPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline BFSRoutingPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<BFSRoutingPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __BFSROUTINGPACKET_M_H

